import { type IImage } from '@/types/utils/IImage'
import { type IItemBorderInfo } from '@/types/utils/IItemBorderInfo'

export interface IProduct {
  attributes: unknown[]
  autogeneratedSlug: string
  borderInfo: IItemBorderInfo
  categories: Array<{ id: number; enabled: boolean }>
  categoryIds: number[]
  combinations: unknown[]
  createTimestamp: number
  created: string
  customSlug: string
  defaultCategoryId: number
  defaultCombinationId: number
  defaultDisplayedPrice: number
  defaultDisplayedPriceFormatted: string
  description: string
  dimensions: { height: number; width: number; length: number }
  discountsAllowed: boolean
  enabled: true
  fixedShippingRate: number
  fixedShippingRateOnly: boolean
  galleryImages: Array<{
    borderInfo: IItemBorderInfo
    hdThumbnailUrl: string
    height: number
    id: number
    imageUrl: string
    orderBy: number
    originalImageUrl: string
    smallThumbnailUrl: string
    thumbnail: string
    thumbnailUrl: string
    url: string
    width: number
  }>
  googleItemCondition: string
  hasFreeShipping: boolean
  hdThumbnailUrl: string
  id: number
  imageUrl: string
  inStock: boolean
  isGiftCard: boolean
  isSampleProduct: boolean
  isShippingRequired: boolean
  lowestPriceSettings: {
    lowestPriceEnabled: boolean
  }
  media: {
    images: Array<{
      id: string
      image160pxUrl: string
      image400pxUrl: string
      image800pxUrl: string
      image1500pxUrl: string
      imageOriginalUrl: string
      isMain: boolean
      orderBy: number
    }>
    videos: unknown[]
  }
  name: string
  nameYourPriceEnabled: false
  options: Array<{
    choices: Array<{
      text: string
      textTranslated: {
        [key: string]: string
      }
      priceModifier: number
      priceModifierType: string
    }>
    defaultChoice: number
    name: string
    nameTranslated: {
      [key: string]: string
    }
    required: boolean
    type: string
  }>
  originalImage: IImage
  originalImageUrl: string
  price: number
  priceInProductList: number
  productClassId: number
  relatedProducts: {
    productIds: unknown[]
    relatedCategory: {
      categoryId: number
      enabled: boolean
      productCount: 1
    }
    seoDescription: string
    seoTitle: string
  }
  shipping: {
    disabledMethods: unknown[]
    enabledMethods: unknown[]
    flatRate: number
    methodMarkup: number
    type: string
  }
  showOnFrontpage: number
  sku: string
  smallThumbnailUrl: string
  tax: {
    defaultLocationIncludedTaxRate: number
    enabledManualTaxes: unknown[]
    taxClassCode: string
    taxable: boolean
  }
  thumbnailUrl: string
  unlimited: boolean
  updateTimestamp: number
  updated: string
  url: string
  volume: number
}
